version: "3.8"

services:
  yolo-client:
    image: silvestor/yolo-client:v1.0.0
    build: ./client
    container_name: yolo-client
    ports:
      - "3000:80"
    depends_on:
      - yolo-backend
    networks:
      - app-net

  yolo-backend:
    image: silvestor/yolo-backend:v1.0.0
    build: ./backend
    container_name: yolo-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://app-ip-mongo:27017/yolomy
    depends_on:
      - app-ip-mongo
    networks:
      - app-net

  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - app-mongo-data:/data/db

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 

volumes:
  app-mongo-data:
    driver: local
