
---
- name: Pull image from repository
  docker_image:
    name: silvestor/yolo-client:v1.0.0
    source: pull

- name: Build frontend Docker image
  command: docker build -t frontend-image .
  args:
    chdir: "{{ compose_file }}client"
  tags: frontend